### ISSUE TITLE
TransactionStatus card to appear before hitting the submit button, lock the form after hitting submit

### ISSUE THREAD

**Issue by goldsteinsveta** [paritytech/parity-bridges-ui#108]
1. Once all fields are filled correctly, the TransactionStatus card should appear above the Submit button
2. On submit, all fields and Submit button have to be disabled. 
3. The disabled Submit button (or component placed instead of the Submit button) should show that transaction is in progress indicating that user has to wait. Alternatives CTAs are: "See in my local storage" opens the history drawer, "New transfer" cleans up the form or its parts for the new transaction

Effectively you see TransactionStatus card in the main UI only in two cases: when you have filled the form correctly and did not hit submit yet, and in the disabled (after submit) main UI form that "holds" values of the most recent transaction. Potentially the card in the disabled UI could be the only place where we live-update at this prototype stage

<img width="837" alt="Screenshot 2021-05-11 at 17 51 53" src="https://user-images.githubusercontent.com/8782596/117846678-f1ab6900-b281-11eb-8779-22ba3d78157c.png">

**Comment by goldsteinsveta** [comment]
pls address this discussion here https://github.com/paritytech/parity-bridges-ui/pull/107#discussion_r623631186

**Comment by wirednkod** [comment]
> pls address this discussion here #107 (comment)

No need - as steps are created on the parent component and will never be an empty array

**Comment by goldsteinsveta** [comment]
related to #157
