### ISSUE TITLE
Large balance in `amount` crashes the app

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-ui#111]
![image](https://user-images.githubusercontent.com/581548/116780988-40862100-aa80-11eb-8a9b-681d69c9325e.png)

**Comment by hbulgarini** [comment]
@wirednkod , as you will revisit the whole process in this issue please take into account that when you set an incorrect character and you delete it , the validation error message does not get reseted.

steps to reproduce the issue:
1) on the amount field enter not allowed character like `C` or `#`.
2) delete and leave the input empty.

Error message remains even when the input is empty.
