### ISSUE TITLE
Warn / Error in case you attempt to send more than your current balance.

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-ui#112]
We should present a warning if the `amount` to send is larger than current derived balance.

**Comment by wirednkod** [comment]
Do we need to keep in mind just that the amount attemped to be sent is more than the current or we need to keep in mind also the fees?

Case 1 we dont care about fees : If user owns 1 MLAU and tries to send 1 MLAU -> system allows it
Case 2 we care about fees : If user owns 1 MLAU and tries to send 1 MLAU -> system does not allow it cause the "cost" is 1.0002 including the fees

**Comment by tomusdrw** [comment]
So far fees are deducted from source account, the transfer happens on target account though.

We should make sure that you have:
1. Enough source tokens to cover the fees + transaction cost.
2. Enough target tokens to cover the transfer amount.

I'd rather `warn` than prevent the user from sending, cause sometimes you might want to send some transaction knowing that you will receive the funds (for instance in previous bridge transfer).
