### ISSUE TITLE
Receiver input may get into weird states

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-ui#117]
To reproduce:
1. Paste recipient address `5sauUXUfPjmwxSgmb3tZ5d6yx24eZX4wWJ2JtVUBaQqFbvEU` - it should display `derived` in the bottom.
2. Select sender account (or change it)
3. ???
4. The bottom part of receiver input disappears.

**Comment by hbulgarini** [comment]
Solved #138 & #165
