### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-ui#13]
The code has a header which refers to a `LICENSE` file which I haven't been able to find.

We should also double check what license to use for this repo (is Apache fine, or should we be more conservative and go with GPL3 for example).

**Comment by tomusdrw** [comment]
Good catch, @hbulgarini  please switch to GPL3 - that's the default license we use, I see no reason to change this to Apache.

**Comment by hbulgarini** [comment]
Actually that header was inherited from the previous bridge-ui project. As the header mentioned paritytech i thought that was the right license. I will switch to use the same license header as the common repository

**Comment by hbulgarini** [comment]
closed #14
