### ISSUE TITLE
Design error components

### ISSUE THREAD

**Issue by wirednkod** [paritytech/parity-bridges-ui#176]
We need to have specific error show component that will show all the different errors that can come for a process.

Description updated by @hbulgarini

**Comment by goldsteinsveta** [comment]
There are three types of errors (and error components) that should be designed and implemented, related to:
- App and connection
- User input
- Submitted extrinsic processing (hard to detect, ideally should be prevented at user input stage)

**Comment by goldsteinsveta** [comment]
@wirednkod, @hbulgarini, @tomusdrw I've added error [page in the design doc](https://www.figma.com/file/OqRXj7Th4uZhSWjNQn8CmH/?node-id=1395%3A30293). Screenshots from there:

App error:

<img width="640" alt="Screenshot 2021-07-20 at 17 50 13" src="https://user-images.githubusercontent.com/8782596/126356789-d0707384-2e2e-4493-987f-f3220a79fdb7.png">

Input error:

<img width="640" alt="Screenshot 2021-07-20 at 17 55 49" src="https://user-images.githubusercontent.com/8782596/126356838-e7e1885d-076c-4b9e-bad8-195e71392996.png">

Submitted extrinsic / subscription error:

<img width="640" alt="Screenshot 2021-07-20 at 17 54 02" src="https://user-images.githubusercontent.com/8782596/126356979-4e8c4fdd-1778-4a3d-8608-a94e5bc74838.png">
