### ISSUE TITLE
TransactionStatus card, when in the history drawer, should display Sender and Receiver accounts

### ISSUE THREAD

**Issue by goldsteinsveta** [paritytech/parity-bridges-ui#199]
[@Figma](https://www.figma.com/file/OqRXj7Th4uZhSWjNQn8CmH/Product-Bridges-UI?node-id=642%3A18201)
<img width="745" alt="Screenshot 2021-06-23 at 16 20 33" src="https://user-images.githubusercontent.com/8782596/123113918-3577bd80-d43f-11eb-86ed-f9ebc770c2ec.png">

**Comment by hbulgarini** [comment]
To be followed in #299
