### ISSUE TITLE
TransactionStatus card should have "Payload" and "Decoded Call" modes

### ISSUE THREAD

**Issue by goldsteinsveta** [paritytech/parity-bridges-ui#200]
<img width="1131" alt="Screenshot 2021-06-23 at 16 48 46" src="https://user-images.githubusercontent.com/8782596/123118478-f5b2d500-d442-11eb-9f7e-7f6e749d6d73.png">

Optional: Payload should be a default mode for CustomCall action

**Comment by hbulgarini** [comment]
@goldsteinsveta  i found the library [react-json-view](https://github.com/mac-s-g/react-json-view) which empowers the JSON.stringify and it adds additional features like collapse, copy ,etc. Take into account that some properties from the payload contains quite a few elements so this tool helps to visually display it better using collapse feature. Here some screenshots:

![Screen Shot 2021-06-28 at 10 31 47](https://user-images.githubusercontent.com/12089572/123644933-3d977a80-d7fc-11eb-98fd-97b7a2378e34.png)
![Screen Shot 2021-06-28 at 10 31 47](https://user-images.githubusercontent.com/12089572/123645016-51db7780-d7fc-11eb-9e94-b1bf7c1f7764.png)
![Screen Shot 2021-06-28 at 10 31 55](https://user-images.githubusercontent.com/12089572/123645034-5738c200-d7fc-11eb-88c0-f20a406a6b8e.png)
![Screen Shot 2021-06-28 at 10 32 13](https://user-images.githubusercontent.com/12089572/123645050-5b64df80-d7fc-11eb-8fd5-9d8d8d82ea17.png)


what do you think?

**Comment by tomusdrw** [comment]
We should keep it simpler (no toggles, imho no extra library needed) and:
1. `SourceAccount` should be formatted as hex.
2. `Call` should be decode using `target` chain custom types and displayed in a readable form, not a set of bytes.

**Comment by hbulgarini** [comment]
> 1. `SourceAccount` should be formatted as hex.

Can i show the account value as:

origin: {
  "SourceAccount": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
}

**Comment by tomusdrw** [comment]
Yes, SS58 formatting with (source) network prefix would be best. We don't necessarily need the raw hex form, I didn't phrase that properly :)

**Comment by hbulgarini** [comment]
> Yes, SS58 formatting with (source) network prefix would be best. We don't necessarily need the raw hex form, I didn't phrase that properly :)

Something like :

{
  "SourceAccount": "48::5sauUXUfPjmwxSgmb3tZ5d6yx24eZX4wWJ2JtVUBaQqFbvEU"
}

or

origin: {
CallOrigin::SourceAccount( "48::5sauUXUfPjmwxSgmb3tZ5d6yx24eZX4wWJ2JtVUBaQqFbvEU")
}

it's a free text, you can choose whatever format it makes more sense...

**Comment by tomusdrw** [comment]
`5sauUXUfPjmwxSgmb3tZ5d6yx24eZX4wWJ2JtVUBaQqFbvEU` already contains the network prefix, no need to prepend it. The first example looks better IMHO.

**Comment by goldsteinsveta** [comment]
closed with #203
