### ISSUE TITLE
Build Docker image on CI and publish to docker hub

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-ui#201]
Follow up on #87

**Comment by wirednkod** [comment]
@tomusdrw as advised I have added this in personal docker hub. With this issue you want to update

**Comment by tomusdrw** [comment]
> With this issue you want every time CI runs to create a new docker image and push it to docker hub (paritytech)?

Exactly. We should be publishng only when CI is running on `master`, not on every PR. I suspect there is an existing GHA available - for tests you can use your personal docker hub and we can later ask the devops team for paritytech configuration.

**Comment by tomusdrw** [comment]
It should be possible to change the URLs of nodes via `environment` parameters to a **built** image. I think the only way to do it (although hacky) is to actually search-and-replace the built files.

See https://github.com/paritytech/parity-bridges-common/pull/1047 for some context - basically we would like the local version of docker compose to be pointing to local instances of the nodes.
