### ISSUE TITLE
Display message dispatch status in UI

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-ui#202]
Currently after dispatching the message on target chain we deliver the confirmation with the result back to the source chain if it was dispatched successfully (see  https://github.com/paritytech/parity-bridges-common/issues/547) - for instance we send a transfer of TAR (target) tokens across the Source->Target bridge and we want to be sure that not only this message was delivered but also that this transfer actually succeeded on the target chain (for instance the account got created and not wiped out due to too low ED, etc). 

UI should display the dispatch result status as well. Currently we only display if the delivery was successful and there is no info about the actual **dispatch**.

UI can actually inspect the dispatch status directly on the target chain (i.e. it doesn't need to wait for that info to be delivered back to the source chain).
There are two possible ways how to do it:

1. Inspect the events at the exact block that the message was delivered and check this (could have been done even without #547)
2. Inspect the messages pallet storage to see the delivery status bit that was introduced in #547

CC @goldsteinsveta

**Comment by hbulgarini** [comment]
Diving into the PR code i suspect the event to be catch is the `MessageDispatched` happening on the targetChain.

https://github.com/paritytech/parity-bridges-common/pull/935/files#diff-1b829a7eb55d63ca86b8cf4eae6a7836662f642ce985f17fe24fbd732f1d0606R1032
