### ISSUE TITLE
Pay dispatch fees on target chain

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-ui#266]
Details: https://github.com/paritytech/parity-bridges-common/issues/561

**Comment by hbulgarini** [comment]
@tomusdrw , could you please guide me a little bit more about the process here?

I suspect that in order to have this features the following changes need to happen:

1) Calculate weight and fee for the delivery on the source ( only funds to be deducted from native account )
2) Calculate weight and fee for the dispatch call on the target.
3) Modify payload in order to dispatch the message setting the fee payment on the target chain.

**Comment by tomusdrw** [comment]
1. On the source chain the fee calculation is going to be the same (using the runtime api), but if the transaction is configured to pay fees at target chain (`dispatch_fee_payment: DispatchFeePayment::AtTargetChain`), the returned value will not include the dispatch fees.
2. Dispatch fee needs to be calculated separately on the target chain, by first getting the `weight` and then getting the fee (or using something like `paymentInfo`). Note that the dispatch fee will be deducted from the companion account, not the source account - that needs some good indication in the UI CC @goldsteinsveta 
3. Yup, that's a matter of adding correct `dispatch_fee_payment` to the message payload.

**Comment by hbulgarini** [comment]
@tomusdrw : 

In the case of paying the fees on the target chain, do i have to reach a different state call than `ToMillauOutboundLaneApi_estimate_message_delivery_and_dispatch_fee` ? ( in case Rilato is the source chain ).

With the same process for calculating the fee that we have now , but adding the `dispatch_fee_payment` indicating the `AtTargetChain` value, the estimated fee returned is `2.609061813 RLT` ( should much less i suspect )

Also when i execute the transaction , the amount deducted from the source chain native account in terms of fee payment is `4.1512 RLT` ( much higher than indicating source target ) and almost nothing is deducted from the target companion account.

I have to say that the weight provided in the payload is the one calculated from the target call. 
In the case of a transfer, here is the call:

```
          call = (await targetApi.tx.balances.transfer(receiverAddress, transferAmount || 0)).toU8a();
          // TODO [#121] Figure out what the extra bytes are about
          call = call.slice(2);
          logger.info(`balances::transfer: ${u8aToHex(call)}`);
          weight = (
            await targetApi.tx.balances.transfer(receiverAddress, transferAmount || 0).paymentInfo(account)
          ).weight.toNumber();
        }
```

My understanding is that if the parameter `dispatch_fee_payment` in the payload contains the value `AtTargetChain` (even if the weight is the one related to the target call) the fee returned from the state call should be the one only linked to the delivery on the source, right? Or should i calculate the weight of the delivery call specifically in order to get the right fee?

This is the code that gets the fee:

```
      const payload = {
        call: compactAddLength(call!),
        origin: {
          SourceAccount: account!.addressRaw
        },
        // PayFee -> enum = AtTargetChain | AtSourceChain
        dispatch_fee_payment: {
          [PayFee.AtTargetChain]: '()'
        },
        spec_version: targetApi.consts.system.version.specVersion.toNumber(),
        weight
      };

      const payloadType = createType(sourceChain as keyof InterfaceTypes, 'OutboundPayload', payload);
      logger.info(`OutboundPayload: ${JSON.stringify(payload)}`);
      logger.info(`OutboundPayload.toHex(): ${payloadType.toHex()}`);
      const messageFeeType = createType(sourceChain as keyof InterfaceTypes, 'MessageFeeData', {
        lane_id: laneId,
        payload: payloadType.toHex()
      });

       // estimatedFeeMethodName = ToMillauOutboundLaneApi_estimate_message_delivery_and_dispatch_fee
      const estimatedFeeCall = await stateCall(sourceChain, estimatedFeeMethodName, messageFeeType.toHex());

      const estimatedFeeType = createType(sourceChain as keyof InterfaceTypes, 'Option<Balance>', estimatedFeeCall);
      const estimatedFee = estimatedFeeType.toString();
      return { estimatedFee, payload };
```

I feel i'm missing something.

**Comment by hbulgarini** [comment]
I wonder if i should read the estimated fee on the source using this function: 

```
fn estimate_delivery_transaction(
		message_payload: &[u8],
		include_pay_dispatch_fee_cost: bool,
		message_dispatch_weight: WeightOf<Self>,
	) -> MessageTransaction<WeightOf<Self>>;
```

https://github.com/paritytech/parity-bridges-common/pull/911/files#diff-897e256de9c8a438ed66ad3d31b04dc3b6f69648f84f64961a5bfce86c7f942cR104

**Comment by tomusdrw** [comment]
> In the case of paying the fees on the target chain, do i have to reach a different state call than ToMillauOutboundLaneApi_estimate_message_delivery_and_dispatch_fee ? ( in case Rilato is the source chain ).

No, this API is fine, but just make sure to construct the right payload with `dispatch_fee_payment: AtTarget`.  The runtime API calls the `estimate_message_dispatch_and_delivery_fee` transaction, which in turn adds fees for couple of transactions (including the `estimate_delivery_transaction` function you've mentioned).


> With the same process for calculating the fee that we have now , but adding the dispatch_fee_payment indicating the AtTargetChain value, the estimated fee returned is 2.609061813 RLT ( should much less i suspect )

Is it different with `AtSourceChain`? If it is then it's okay, Rialto/Millau are not well tuned.


> Also when i execute the transaction , the amount deducted from the source chain native account in terms of fee payment is 4.1512 RLT ( much higher than indicating source target ) and almost nothing is deducted from the target companion account.

This needs a bit more concrete example - is it a transfer? Is it successful? How much is being transferred? etc. AFAIK the `estimate_message_delivery_and_dispatch_fee` is the upper bound of how much fee is going to be collected, right @svyatonik ?


> I have to say that the weight provided in the payload is the one calculated from the target call.

This is okay.

> the fee returned from the state call should be the one only linked to the delivery on the source, right?

Not really, no. The fee should includes all bridge-related transactions that need to be sent: delivery of the message across the bridge (source -> target), delivery of confirmation (target -> source), relayer reward (10%), etc. It's going to be much larger than regular fee.

**Comment by svyatonik** [comment]
> This needs a bit more concrete example - is it a transfer? Is it successful? How much is being transferred? etc. AFAIK the estimate_message_delivery_and_dispatch_fee is the upper bound of how much fee is going to be collected, right @svyatonik ?

`estimate_message_delivery_and_dispatch_fee` returns a minimal fee which will pass runtime checks. If sender tries to pay lesser fee, send will fail. If he'll pay larger fee, send will succeed.

Re specific fees (4 RLT/2 RLT) - concrete example would help, as Tomek has said. When you're paying dispatch fee `AtTargetChain`, this amount is deducted from the `delivery_and_dispatch_fee` at the source chain. But at the same time, `delivery_and_dispatch_fee` is increased by the cost of `Currency::transfer` at the source chain. So it may be larger than `AtSourceChain`-fee.

**Comment by hbulgarini** [comment]
Sure.  This is the payload for a token transfer transaction from Rialto to Millau of 10 MLAU.

```
{
  "call": {
    "callIndex": "0x0900",
    "args": {
      "dest": "75DSWq62jcgwcfz15DKgG3w9z35L8fYAUDUcKF1K4zCfv2yc",
      "value": 10000000000
    }
  },
  "origin": {
    "SourceAccount": "5smXQvbC88CDjy8SCpmPjEk4EDMoUTyvCvq2w3HhWj4pYQqz"
  },
  "weight": 198268000,
  "spec_version": 1,
  "dispatch_fee_payment": {
       "AtTargetChain": "()"
  }
}
```

This is the PayloadHex: 
```
0x010000006054d10b0000000002dc4f025295b81c0c00384a4b62e1a41dbe0bcba16b18754ef46296bd8c5a2e7b01a00900dc4f025295b81c0c00384a4b62e1a41dbe0bcba16b18754ef46296bd8c5a2e7b0700e40b5402
```

Estimated Rialto fee: 2.614473057 RLT
Amount deducted on the source native account: 5,489 RLT

Fee payed on the companion target account: 1.8094 MLAU.

Rialto: Include message in block 5502
Millau: Deliver message in target block 5509

Message Nonce: 7291

**Comment by tomusdrw** [comment]
Would be great if paying fees on target chain became the new default. Paying on the source chain should be optional (can be even hidden/expert setting).
