### ISSUE TITLE
Search on sender selector should support network

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-ui#277]
With many accounts it's hard to actually switch the network. It's quite apparent in case you have accounts that are enabled for all networks - filtering the name still displays at least two.

I think it would be cool to type in "Kusama/Rialto/Millau" in the search box and filter out specific network-account, or have some other way to collapse the entire network.

**Comment by hbulgarini** [comment]
I agree that something needs to be done for this, but i'm not sure that the input search field is the best one for filtering networks. In this [comment](https://github.com/paritytech/parity-bridges-ui/issues/168#issuecomment-903745094) i proposed to have a different filter for networks.

**Comment by goldsteinsveta** [comment]
I'd love to search by network too. "<Network> <Account>" would be how I would type my search string, ig "kusama governance" or "rialto test6"

**Comment by hbulgarini** [comment]
OK. I think the preference for the search bar is quite clear. Let's go on that path then.
