### ISSUE TITLE
Unable to decode storage system.events:: createType(Vec<EventRecord>)

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/parity-bridges-ui#293]
On Rialto network when the API is trying to read certain events from ( not sure yet if it related to relayer or mesage pallet ), the api is not able to decode the event:

`
2021-09-22 18:20:59        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage system.events:: createType(Vec<EventRecord>):: decodeU8a: failed at 0x0000000000020000… on : {"phase":"Phase","event":"Event","topics":"Vec<Hash>"}:: decodeU8a: failed at 0x020000000000a0b8… on event: {"index":"EventId","data":"Null"}:: findMetaEvent: Unable to find Event with index 0x0200/[2,0]
`

I wonder if the issue started since this [PR](https://github.com/paritytech/parity-bridges-common/pull/1053) was merged on the common repo.

**Comment by tomusdrw** [comment]
Make sure to upgrade to latest `api` as well, might be some substrate change, since the PR also bumps substrate version.

**Comment by hbulgarini** [comment]
For reproducing the error you can just go to [polkadotjs for Rialto](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwss.rialto.brucke.link&types=eNq9V21v2zYQ%2FiuBPnWAAixOE2RdUcBJusVbUgdxln0YCoGRzjZXmVRJqp0X5L%2F3ji8iJdn91PaLIN4d74V8%2BPD4lB0eHmWvshte16w9uN82oLPcD6dVpUBrVE%2FLUrbCzKpOd85qJkpAXXv6MkprWX64YnqN8quTo0lf8a7dPIIaTLkCVpHwKWuYAmEKP33oMM9EmH4hNw0rzeuR6zdopQ0zUCgpzU4n8J9RXGhe6v02FV%2BBjqpLN3wOGfsxZlzLFa3OA5Q%2BF6eaGdi8GdqTkOYUgHXQz9ysbTU0uz2j1KetWUvFDQd9sWZiRatL2iDfzioyczp9rzjc7SthAax%2B%2BBlV%2FgdnSaFB6JYSjv%2FO0tvh6FbBHW4031DsZPCM1RweTlB4x1ltZIcUN4xIuWlrw8MwqBOwHE3OojhFy%2BTktK%2BIaDkmHDnNPrQMHe5Ay8j1CC1jJ2O0jG06tDhVREtv3EdLqurQMhR%2BL7SMS%2Fg%2BaDl2i7%2BR4sB4tFxL%2BaFtFrJVFg0DsHiWWfCVsLVatR9h6AbKB1CaSxFBATXbgkJe6nOUixAlfe1s00hloIpgWvu%2F7FzxatVp8kzBx5ZjesW%2FrTZ8yUtmXPxHKWkFuC6WXLCa%2Fw8UxUs15szqYu2wOW9ozmvvult3u%2BfdZi3AYoTFTaWkg%2FaaI4TQL5iCUxy0xkpwvq3tn%2Fbs14OX791mc2FlttBrJiCObnCV2QreyZS3XVZeZW1fzKr8AJU%2FxSl%2FwtYCGN25%2BN4xnjJy9or2KnVOiYlHXO%2FKb9BwA5ySvFwyw8i3cobhgPwlFHxmqoLggaBcM22KUoolVxuoCht7R%2BjR3MQ%2Fwb%2FDTJ5t3FSKegk1%2FwQKKu9Ok6uxEF09wooTBHpxkSsErcxAWHHdMFOuC8QQopkCnXODFZL3eWtG61AjH2GVK0DQ4%2B%2BeKmktrJ2CEjDDvWayrsisFY1qxVfWzI9DFg3b1pIl9dx6QZ4tgeb%2Fht84LWhTevJwnzfsYwsXrCbaiNpQundA7pzTqOqcPmUaj36B%2B%2BDPfsoEefYZ%2BGpNvPa3%2B8GiFXc7RGHnbpBsBVZQYIEbvD5o370Yg2NEK8yz0uU7rgFrTpymBO0ox1PsCzo890ytwHjck3DASvlBQnDJgJlWATno2VPdA1Yjmt2RfprV1LhJlhhCYlPjUkuE5Cql29TH22pycnL0S7ykF2ogeFtWGnFjiej4%2BL3z5k%2FMLV6cy%2FnSHhy3nIVj20CPQ160t7JUOLdoaK7HzcLJrDt3ZdIhEISbPhvpAi91Zdui%2Flnw2h3nFNMduu%2BhNdTi6WD742raRWd6QU0LBW87FRKB1WF12LFYQhtUH6iu4KLwrEC2SOxDSyMNXl4JNQ7XakrriFNt3gFU8SRHKhtdF5FXhqcc3WIDUWK7wC2CcQsRoV9ZT2%2FQtXmpiW8de%2FdrOFgepqf2vkx6pQDfCcntKah6CTVxkGTq73rveEc0bBFs%2B5EEIg75pnXiuoaEwv05KMD2Gr8rJqqG%2FdHvZPBqpH3oGoKuSJ9jnn2SeNUU1MDjpjtsUYheq%2BSame4V0H8V5JbZu8bTPwbwiuieBSNN8jIYt6v958H4ydBdPqmb8Rtpx0r2zIbeQrvYf7gibpliGzAD1nRp3UtnjD20v7%2Fu7Nl1DyHiyQdsHiu7FxeygvQ19PwF1nFexg%3D%3D) and explore any block with the problematic event ( it is not hard to pick one randomly)

**Comment by hbulgarini** [comment]
> Make sure to upgrade to latest `api` as well, might be some substrate change, since the PR also bumps substrate version.

Yes, that was done on the PR https://github.com/paritytech/parity-bridges-ui/pull/290

**Comment by hbulgarini** [comment]
CC: @svyatonik

**Comment by hbulgarini** [comment]
Issue has gone after merging PR #291 and fixing some types definitions.
