### ISSUE TITLE
Design for select which chain pays the fee for the dispatch call.

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/parity-bridges-ui#297]
Related: #266

At the moment the code base supports paying the dispatch fee on the target chain, but we need to define a proper UX process to let the user to choose where he/she wants to pay the fee.

**Comment by hbulgarini** [comment]
CC: @goldsteinsveta

**Comment by hbulgarini** [comment]
hey, i really like the design and the approach. Anyway i have some comments:

1) My understanding is that what we are letting the user to decide is where he/she wants to pay the dispatch fee, meaning that source and target fees will be spent in both chains independently from the option chosen.
Based on this i think the dropdown should only show: `Source Chain` or `Target Chain`. Also we might be more specific regarding the label from `Fees payed on` to `Dispatch fee payed on` ?????

Below you have some screenshots for the current work done:

![Screen Shot 2021-11-04 at 10 05 55](https://user-images.githubusercontent.com/12089572/140318513-4d94858d-6c4e-4895-83d0-34a6480ee4d8.png)

![Screen Shot 2021-11-04 at 10 06 05](https://user-images.githubusercontent.com/12089572/140318538-996446a8-368d-45f1-91c8-197df8e16ff3.png)

2) As the link to the design document is broken , i'm not sure about what's the default option usage shown in the screenshot. Is it strictly necessary to implement something to force the default only having two options available?

**Comment by goldsteinsveta** [comment]
1. It's a dispatch fee indeed. I've changed the design doc.
_(Btw the wording for interactions with bridges needs to be thought through, but it's a different very exciting discussion :P)_
2. The default option is Target as per https://github.com/paritytech/parity-bridges-ui/issues/266#issuecomment-919978925
_(Btw I've re-sent you an invite - sorry for that - also feel free to use comment function in Figma for design nits, it's usually easier to discuss and resolve issues right in the design doc)_

**Comment by hbulgarini** [comment]
1. Cool !
2. Ah ! i get it know... yes.. #266 is still not clear AFAIK so i think we can leave this one to be `Source Chain` the default.
