### ISSUE TITLE
Running dashboard on empty chains reports pending message

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-ui#3]
I've run the dashboard and two nodes in the background using:
```
$ ./target/release/rialto-bridge-node --dev --tmp --ws-port 9944
$ ./target/release/millau-bridge-node --dev --tmp --ws-port 9945
```

The dashboard displays pending messages, while there were no messages sent?

![image](https://user-images.githubusercontent.com/581548/108984183-ecca1680-768f-11eb-9ac7-dc7d0bda5507.png)

**Comment by hbulgarini** [comment]
i think that issue is not related to the dashboard itself... is it possible that when the message relayers starts or any other ( component ) sends a message to test the connection?

**Comment by hbulgarini** [comment]
i don't see an offset from the code, but for some reason the `latest_generated_nonce` value retrieved from the api is `1`  and not zero.

**Comment by hbulgarini** [comment]
![Uploading Screen Shot 2021-03-10 at 09.15.46.png…]()

**Comment by hbulgarini** [comment]
It seems this offset was resolved after the pallet name changes.
