### ISSUE TITLE
Put icons on all app

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/parity-bridges-ui#48]

**Comment by hbulgarini** [comment]
Code reference where the icons should be defined per each chain: https://github.com/paritytech/parity-bridges-ui/blob/master/src/configs/substrateProviders.ts

**Comment by goldsteinsveta** [comment]
I close the issue as "all app" uses material UI icons. Unfortunately the linked config is 404, but as I understand this is about network logos. There's icon/ligatures font: https://github.com/goldsteinsveta/web3-regular that I'd use for chains with logos. Chains that are currently supported do not have associated logos at all.
