### ISSUE TITLE
Create switch action component.

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/parity-bridges-ui#51]

**Comment by goldsteinsveta** [comment]
@hbulgarini do you mean this pal here?

<img width="750" alt="Screenshot 2021-04-21 at 16 42 46" src="https://user-images.githubusercontent.com/8782596/115572945-a32d2f00-a2c0-11eb-85e5-0ff889b1b39b.png">

**Comment by hbulgarini** [comment]
Sorry i missed the description . Yes, that action menu but also this task includes the conditional rendering of the selected component ( Transfer, Remark, Call )
