### ISSUE TITLE
Display popover with information about transaction/call 

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/parity-bridges-ui#54]
Before the user hits the transfer button once all the mandatory values were provided there has to be a mechanism to inform the user what it will be executed:

("sending remark with payload 0x123", etc).

**Comment by goldsteinsveta** [comment]
for the reference: 

<img width="494" alt="Screenshot 2021-04-21 at 17 42 47" src="https://user-images.githubusercontent.com/8782596/115582219-058a2d80-a2c9-11eb-90f4-7e2483b5ffdb.png">

**Comment by hbulgarini** [comment]
> for the reference:
> 
> <img alt="Screenshot 2021-04-21 at 17 42 47" width="494" src="https://user-images.githubusercontent.com/8782596/115582219-058a2d80-a2c9-11eb-90f4-7e2483b5ffdb.png">

i would also share this in the issue https://github.com/paritytech/parity-bridges-ui/issues/61

**Comment by hbulgarini** [comment]
I think this need was addressed in #203
