### ISSUE TITLE
Apply styles on Transfer component.

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/parity-bridges-ui#64]
Transfer.tsx component need to apply the following design enclosed in the red square.

![Screen Shot 2021-04-20 at 15 37 18](https://user-images.githubusercontent.com/12089572/115447038-685ac680-a1ee-11eb-9783-bb381087118d.png)

Also a little UX change is needed: Instead of showing the fee as soon as all the information is provided , the `Calculate fees` button needs to show the value when it is clicked.

**Comment by goldsteinsveta** [comment]
based on discussion, I removed the calculate fees step
