### ISSUE TITLE
Apply design to dashboard cards

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/parity-bridges-ui#70]
Move the existing top source / target dashboard to the right pane of the design:

![Screen Shot 2021-04-20 at 15 23 46](https://user-images.githubusercontent.com/12089572/115445575-6859c700-a1ec-11eb-870c-bfa70a21ae0d.png)

**Comment by goldsteinsveta** [comment]
I am still moving this one around. Today I think actually having it on the left is just more normal and I don't quite see the reason to break this convention. Here's some of the latest screen with the sidebar on the left

<img width="1143" alt="Screenshot 2021-04-21 at 16 00 21" src="https://user-images.githubusercontent.com/8782596/115566796-dff62780-a2ba-11eb-9099-b49379c39c28.png">

**Comment by hbulgarini** [comment]
Also take into account that we will not be implementing Address book and History in the short term ... so the left part only would show the dashboard details
