### ISSUE TITLE
Display in accounts the full balance (no SI; with thousand separator) in a tooltip (title attribute is good enough).

### ISSUE THREAD

**Issue by wirednkod** [paritytech/parity-bridges-ui#78]
Revisit this with @goldsteinsveta

**Comment by goldsteinsveta** [comment]
Is it related to #104

**Comment by wirednkod** [comment]
@hbulgarini I think we can close this and re discuss it with #193 . Maybe it is irrelevant at this point.
What do you think?

**Comment by hbulgarini** [comment]
> @hbulgarini I think we can close this and re discuss it with #193 . Maybe it is irrelevant at this point.
> What do you think?

I agree . Let's keep discussing it in #193.
